# See :~ https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: Node CI

on: [push]

# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 18

jobs:

  build:
    name: build & test
    runs-on: ubuntu-latest

    # https://github.com/marketplace/actions/skip-based-on-commit-message
    if: "!contains( github.event.head_commit.message, 'ci skip' )"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
      env:
        CI_SKIP: false

  skip:
    name: skip build & test
    runs-on: ubuntu-latest
    if: "contains( github.event.head_commit.message, 'ci skip' )"
    steps:
    - name: Skip build
      run: echo Skipping build.
    env:
      CI_SKIP: true

# End.
