# See :~ https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml

name: Node CI

on: [push]

# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 22

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build:
    name: build & test
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # https://github.com/marketplace/actions/skip-based-on-commit-message
    # if: "!contains( github.event.head_commit.message, 'ci skip' )"

    steps:
    - uses: actions/checkout@v4
    #  with:
    #    fetch-depth: 1
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build:site --if-present
    - run: npm test

    # Deploy.
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# End.
